### ISSUE TITLE
Blake3Hasher is not a constructor when using in the worker threads

### ISSUE THREAD

**Issue by sureshvenkata12** [Brooooooklyn/blake-hash#29]
When using Blake3Hasher in the worker threads, I get the following error: 

TypeError [Error]: blake_hash_1.Blake3Hasher is not a constructor

**Comment by sureshvenkata12** [comment]
This is the fastest blake3 implementation I've ever tested, so multiple worker support would be awesome! Thank you.

**Comment by Brooooooklyn** [comment]
Please provide the reproduce codes

**Comment by Brooooooklyn** [comment]
I've tested `@napi-rs/blake-hash@1.3.0` with `node:16.13.1` and `macOS:12.0.1 x64`, everything work fine:

### `index.js`

```js
const { Worker } = require('worker_threads')

const worker = new Worker('./worker.js')

worker.on('message', (message) => {
  console.log(message)
})
```

### `worker.js`

```js
const { parentPort } = require('worker_threads')

const { Blake3Hasher } = require('@napi-rs/blake-hash')

const hasher = new Blake3Hasher()
hasher.update('hello')

parentPort.postMessage(hasher.digest('hex'))
```

**Comment by Brooooooklyn** [comment]
Tested on `debian:9` with `node:14.18.2`, also works fine @sureshvenkata12

**Comment by sureshvenkata12** [comment]
Thanks for looking into this. I've been trying to use it in '[ironfish](https://github.com/iron-fish/ironfish)', a blockchain open-source project. 

Node 16.13.1 and I've tried in both ubuntu x86_64 and mac arm64. When I call Blake3Hasher outside the worker context, it works though.

<img width="762" alt="Screen Shot 2021-12-13 at 2 02 30 AM" src="https://user-images.githubusercontent.com/95852756/145791797-a05cc498-605b-4af0-90e8-41c02ac82a8f.png">

**Comment by Brooooooklyn** [comment]
@sureshvenkata12 do you have any codes or git branch I can debug?

**Comment by sureshvenkata12** [comment]
https://github.com/sureshvenkata12/ironfish/tree/newhash
Checkout "newhash" branch 
yarn install
yarn build
./ironfish-cli/bin/ironfish start (you will see the error below)

> 
> TypeError [Error]: blake_hash_1.Blake3Hasher is not a constructor
>     at Object.<anonymous> (ironfish/ironfish/build/src/workerPool/tasks/mineHeader.js:9:19)

**Comment by Brooooooklyn** [comment]
In `ironfish/build/src/workerPool/tasks/mineHeader.js`, the return type of `require('@napi-rs/blake-hash-darwin-x64')` became `{}`, an empty object. I don't know why because the start process of `ironfish` is too  complex.

**Comment by sureshvenkata12** [comment]
Do you have any idea what might be the issue? I will look into it deeper if you have any pointers. I've tried napi-rs/canvas package in the worker, it worked well.

**Comment by Brooooooklyn** [comment]
@sureshvenkata12 thanks for your investigation, I'll dig into this issue when I have time.

**Comment by Brooooooklyn** [comment]
@Brooooooklyn Please try the https://github.com/Brooooooklyn/blake-hash/releases/tag/v1.3.1. It should fix this bug.

**Comment by dguenther** [comment]
v1.3.1 works based on my testing, thanks for the update!

**Comment by sureshvenkata12** [comment]
@dguenther btw, how did you find out me trying "blake-hash" for ironfish? I guess, you will incorporate this into the main, and I will not have any advantage over others now :)

**Comment by dguenther** [comment]
It was just a coincidence! We wanted to test a native addon replacement for `blake3` to address WASM out of memory issues.

**Comment by Brooooooklyn** [comment]
@dguenther You can consider https://napi.rs/ to replace neon in `ironfish` too. It provides more functionality and is easier to use.
