### ISSUE TITLE
Planned next release?

### ISSUE THREAD

**Issue by mat-if** [Brooooooklyn/blake-hash#79]
Hi,

I was looking at the recent changes: https://github.com/Brooooooklyn/blake-hash/compare/v1.3.2..main and noticed a few things that I would love to use. 
Specifically https://github.com/Brooooooklyn/blake-hash/commit/95077d44d1f29de4bdf4c7e0818b1c5b8808b80e and https://github.com/Brooooooklyn/blake-hash/commit/2af3c3002f02e32359151590fb27b445b7ffe06c#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R14

I was curious when the next NPM release would be?

Thanks!

**Comment by Brooooooklyn** [comment]
https://github.com/Brooooooklyn/blake-hash/releases/tag/v1.3.3

**Comment by mat-if** [comment]
Thank you!
