### ISSUE TITLE
Error installing "@napi-rs/blake-hash-android-arm64" via npm and yarn

### ISSUE THREAD

**Issue by parajbs** [Brooooooklyn/blake-hash#90]
Hello LongYinan,

I found a problem.
when I type the command "npm i @napi-rs/blake-hash-android-arm64" I get this error:

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@napi-rs%2fblake-hash-android-arm64 - Not found
npm ERR! 404
npm ERR! 404 '@napi-rs/blake-hash-android-arm64@*' is not in this registry.

When I try to install it with yarn I get this error:

error https://registry.yarnpkg.com/@napi-rs/blake-hash-android-arm64/-/blake-hash-android-arm64-1.3.3.tgz: Request failed "404 Not Found"

can you help with the error
How can I install it via package.json?

**Comment by Brooooooklyn** [comment]
> error https://registry.yarnpkg.com/@napi-rs/blake-hash-android-arm64/-/blake-hash-android-arm64-1.3.3.tgz: Request failed "404 Not Found"

I can download it without any problem. Can you please retry?
